# Generated by Django 2.2.19 on 2021-04-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formResearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('student_id', models.IntegerField(default=0)),
                ('gender', models.CharField(default='Unspecified', max_length=100)),
            ],
        ),
    ]
