# Generated by Django 2.2.20 on 2021-04-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formResearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studyName', models.CharField(max_length=100)),
                ('briefAbstract', models.TextField()),
                ('detailedDescription', models.TextField()),
                ('duration', models.CharField(max_length=3)),
                ('creditsResearch', models.CharField(max_length=4)),
                ('reseacher', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('approvalCode', models.CharField(max_length=20)),
                ('expireDate', models.DateField()),
                ('approved', models.BooleanField(default=True)),
                ('activeStudy', models.BooleanField(default=True)),
                ('minAge', models.CharField(max_length=100)),
                ('maxAge', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NA', "Don't Specify")], default='NA', max_length=2)),
                ('race', models.CharField(max_length=200)),
                ('ethinicty', models.CharField(max_length=200)),
            ],
        ),
    ]
